name: Update Routes with Timestamps

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * *'  # runs daily at midnight UTC

jobs:
  update-timestamps:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install xeuledoc requests beautifulsoup4 python-dateutil

      - name: Run timestamp updater script
        run: python update_timestamps.py

      - name: Commit updated JSON file
        uses: EndBug/add-and-commit@v9
        with:
          add: 'routes-with-timestamps.json'
          message: 'Update routes-with-timestamps.json with latest timestamps'

